name: Go

on:
    - push
    - pull_request

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Setup Go environment
              uses: actions/setup-go@v2.1.3

            - name: Checkout
              uses: actions/checkout@v2

            - name: Build
              run: cd cmd && go build -v

    golangci:
        name: lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: golangci-lint
              uses: golangci/golangci-lint-action@v1
              with:
                  version: v1.29
                  working-directory: cmd
